In [3]:
import pandas as pd
url = 'crabs.csv'
crabs = pd.read_csv(url)
crabs.head(200)

speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [7]:
data = crabs.replace(["F","M","B","O"],[1,0,1,0])
data.head(200)

speies  sex  index  fontallip  rearwidth  length  width  depth
0         1    0      1        8.1        6.7    16.1   19.0    7.0
1         1    0      2        8.8        7.7    18.1   20.8    7.4
2         1    0      3        9.2        7.8    19.0   22.4    7.7
3         1    0      4        9.6        7.9    20.1   23.1    8.2
4         1    0      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       0    1     46       21.4       18.0    41.2   46.2   18.7
196       0    1     47       21.7       17.1    41.7   47.2   19.6
197       0    1     48       21.9       17.2    42.6   47.4   19.5
198       0    1     49       22.5       17.2    43.0   48.7   19.8
199       0    1     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [8]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split # chia ra 7 phan train, 3 phan test
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.preprocessing import StandardScaler

X1 = data['fontallip'].values
X2 = data['sex'].values
X3 = data['index'].values
X4 = data['rearwidth'].values
X5 = data['length'].values
X6 = data['width'].values
X7 = data['depth'].values

y = data['speies'].values

col_X1 = X1.reshape(-1,1)
col_X2 = X2.reshape(-1,1)
col_X3 = X3.reshape(-1,1)
col_X4 = X4.reshape(-1,1)
col_X5 = X5.reshape(-1,1)
col_X6 = X6.reshape(-1,1)
col_X7 = X7.reshape(-1,1)

X = np.hstack((col_X1,col_X2,col_X3,col_X4,col_X5,col_X6,col_X7))

print("Number of columns:", col_X1.shape[0])

print(X[:7][:7])

print(y[:20])


Number of columns: 200
[[ 8.1  0.   1.   6.7 16.1 19.   7. ]
 [ 8.8  0.   2.   7.7 18.1 20.8  7.4]
 [ 9.2  0.   3.   7.8 19.  22.4  7.7]
 [ 9.6  0.   4.   7.9 20.1 23.1  8.2]
 [ 9.8  0.   5.   8.  20.3 23.   8.2]
 [10.8  0.   6.   9.  23.  26.5  9.8]
 [11.1  0.   7.   9.9 23.8 27.1  9.8]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [9]:

X_train, X_test,y_train, y_test = train_test_split(X,y,test_size = 0.3) #test =0.3, train = 0.7

sc =  StandardScaler()
sc.fit(X)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)


print(X_train_std[:5],X_train[:5])

print(y[:5])

[[ 1.29554045 -1.          1.07408634  0.37457656  1.19621246  1.02970478
   1.16196372]
 [ 0.54982312  1.         -0.17323973  0.76415177  0.16821188  0.15097582
   0.16670572]
 [-0.79820435  1.         -0.17323973 -0.20978625 -0.59222691 -0.57493071
  -0.74073541]
 [ 1.00872609  1.          0.58901509  1.27059953  0.80191087  0.74953033
   0.81069619]
 [ 1.43894762 -1.          1.14338223  0.6472792   1.50602086  1.28440883
   1.63032043]] [[20.1  0.  41.  13.7 40.6 44.5 18. ]
 [17.5  1.  23.  14.7 33.3 37.6 14.6]
 [12.8  1.  23.  12.2 27.9 31.9 11.5]
 [19.1  1.  34.  16.  37.8 42.3 16.8]
 [20.6  0.  42.  14.4 42.8 46.5 19.6]]
[1 1 1 1 1]


In [10]:
model = Perceptron(max_iter= 40, eta0 = 0.1, random_state = 0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác mô hình: ', accuracy_score(y_test, y_pred))

[1 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0
 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0]
[0 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0
 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0]
Độ chính xác mô hình:  0.9333333333333333


In [11]:
model = Perceptron(max_iter= 1000, eta0 = 0.3, random_state = 0)
model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác mô hình: ', accuracy_score(y_test, y_pred))

[1 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0
 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0]
[0 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0
 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0]
Độ chính xác mô hình:  0.9333333333333333
